name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Build and deploy
        run: |
          docker-compose up -d
          
      - name: Install pytest
        run: |
          docker-compose exec -T backend pip install pytest
          
      - name: Run tests
        run: |
          docker-compose exec -T backend python -m pytest

      #- name: Lint check
      #  run: |
      #    # Instale as dependências necessárias para a verificação de lint
      #    docker-compose exec -T frontend npm install eslint --save-dev
      #    docker-compose exec -T frontend npm install eslint-plugin-react --save-dev

          # Execute o comando de verificação de lint
      #    docker-compose exec -T frontend npx eslint --fix src


      - name: Tear down containers
        run: docker-compose down
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose build x-webserver
          docker-compose push x-webserver
