name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v1

      - name: Build and run containers
        run: |
          docker-compose up -d --build
          docker-compose ps

      - name: Run tests
        run: |
          # Execute seus testes aqui, por exemplo:
          docker-compose exec api python -m pytest

      - name: Tear down containers
        run: docker-compose down
