name: CI

on:
  push:
    branches:
      - tests
  pull_request:
    branches:
      - tests

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Build and deploy
        run: |
          docker-compose up -d
          
      - name: Install pytest
        run: |
          docker-compose exec -T backend pip install pytest
          
      - name: Run tests - js
        run: |
          docker-compose exec -T frontend npm test
                    
      - name: Run tests - python
        run: |
          docker-compose exec -T backend python -m pytest


      - name: Tear down containers
        run: docker-compose down

