name: CI

on:
  push:
    branches:
      - lint
  pull_request:
    branches:
      - lint

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
      - name: Build and deploy
        run: |
          docker-compose up -d

      - name: Lint check
        run: |
          # Instale as dependências necessárias para a verificação de lint
          docker-compose exec -T frontend npm install eslint --save-dev
          docker-compose exec -T frontend npm install eslint-plugin-react --save-dev
          
          # Execute o comando de verificação de lint
          docker-compose exec -T frontend npx eslint --fix src

